backend:
  name: github
  repo: dagklassical/dag-www
  auth_type: pkce
  app_id: 3eedf5a01f4ca8ba330afc13fdfbe916491ec49134d8bc5cb7f743e06023ac95
  base_url: https://github.com
  branch: main

media_folder: "public/images"
public_folder: "/dag-www/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "discografia"
    label: "Discografía"
    folder: "src/content/albums"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Artista", name: "artist", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
