backend:
  name: github
  repo: dagklassical/dag-www
  branch: main
  auth_type: pkce
  client_id: Ov23liuqrLJ3wpuVYZj9
  auth_endpoint: https://github.com/login/oauth/authorize
  auth_token_endpoint: https://github.com/login/oauth/access_token

site_url: https://dagklassical.github.io/dag-www
display_url: https://dagklassical.github.io/dag-www

media_folder: "public/images"
public_folder: "/dag-www/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}